"""empty message

Revision ID: 0c118ef57dbb
Revises: 859d8d31f93e
Create Date: 2022-02-23 16:16:59.377271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c118ef57dbb'
down_revision = '859d8d31f93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'symbol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'symbol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
