"""empty message

Revision ID: 225f41157b39
Revises: 9d6dee999742
Create Date: 2022-02-23 14:04:25.312152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225f41157b39'
down_revision = '9d6dee999742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbols')
    # ### end Alembic commands ###
