"""empty message

Revision ID: 5a498330c1d9
Revises: 0c118ef57dbb
Create Date: 2022-02-23 16:19:54.479029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a498330c1d9'
down_revision = '0c118ef57dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_prices_date'), 'prices', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_date'), table_name='prices')
    op.drop_column('prices', 'date')
    # ### end Alembic commands ###
