import yfinance as yf
import time
from datetime import timedelta
import sys

def get_data(stock):
    data = yf.download(stock, start="2014-01-04", end="2022-01-04")
#     print(data['Close'])
    return data

# get at 08.02.2022 from https://www.slickcharts.com/sp500
sp500 = "AAPL MSFT AMZN GOOGL GOOG TSLA NVDA BRK-B FB UNH JPM JNJ PG V HD BAC XOM MA PFE CVX DIS ABBV AVGO ADBE KO PEP CSCO TMO WFC COST ABT CMCSA VZ ACN CRM WMT QCOM INTC MRK MCD LLY NKE DHR NFLX T UPS PM LOW TXN UNP INTU LIN MS AMD NEE BMY CVS PYPL RTX SCHW MDT HON C ORCL AMGN GS AMAT IBM COP AXP BA BLK NOW \
    PLD SBUX AMT GE ANTM CAT DE TGT BKNG ISRG SPGI LMT ZTS MDLZ MMM MO MU PNC CB CME ADP ADI TFC TJX SYK LRCX USB DUK GILD CCI MMC BDX CHTR CSX CI GM EL ICE SO TMUS F FIS EW CL SHW EOG REGN COF D ITW NSC PGR AON FISV EQIX VRTX ATVI BSX FDX ETN KLAC EMR FCX MRNA APD SLB WM NOC HCA ILMN HUM PSA MCO ADSK NXPI XLNX \
        AIG PXD NEM MET MPC GD SPG JCI BK DG IQV CNC TEL ROP APH SNPS ECL CTSH INFO MAR MSCI PRU AEP KMB DOW IDXX SRE BAX HPQ GPN ORLY LHX EXC A TRV ADM AZO MCK FTNT HLT GIS DLR MCHP SYY CMG DXCM CDNS AFL MSI CARR PSX DD PH STZ EA O PAYX WMB TT EBAY XEL YUM ALGN VLO CTVA OXY STT PPG SIVB ALL APTV AMP DFS WBA\
             SBAC WELL OTIS MTD RMD TROW CBRE AVB KMI PEG FITB ROST CTAS TDG DVN BIIB PCAR IFF CMI ROK GLW AJG MTCH NUE VRSK MNST FRC AME WY FAST ED KEYS DLTR EQR ES KR BLL WEC HSY WST WTW TSN HAL TWTR ANSS ODFL EFX AWK OKE DHI ANET EXPE CPRT CERN EXR ZBRA RSG LH ARE LUV CDW HES DAL SWK LYB ALB NTRS EPAM MKC\
                  LEN KEY TSCO CHD IT KHC HIG MAA VMC BKR SYF HBAN EIX RF DOV ZBH MLM MTB DTE CFG PKI FTV URI FE AEE SWKS PPL STE FANG HPE IR ETR STX BBY DRE ESS GWW VRSN RJF NDAQ ABC VIAC TTWO VFC VTR WAT ULTA TDY SBNY NTAP FLT TYL COO ENPH CMS CTRA GRMN PFG TER HOLX EXPD AKAM VTRS GPC DRI IP CINF MGM RCL\
                       POOL CLX AMCR TRMB CNP NVR GNRC CTLT PEAK CE ETSY KMX CCL BR MRO MPWR CZR CRL CAG WAB J OMC MOS NLOK UDR BXP DGX XYL EMN TECH DPZ WDC FDS BRO PAYC JBHT K CF CAH TXT LVS IEX AVY CEG MAS LKQ EVRG SJM BBWI LNT TFX AAP LYV AES KIM IPG QRVO UAL PKG MKTX FMC ATO INCY PWR BIO HRL RHI IRM ABMD\
                            FOXA CMA APA CBOE SEDG WRB PHM HST HWM CTXS WHR LNC LDOS L JKHY FBHS BF-B FFIV PTC WRK HAS CHRW ZION LUMN RE XRAY SNA JNPR NI AAL TPR ALLE REG HSIC BWA CDAY PNR AOS NRG GL UHS SEE DXC WYNN LW TAP AIZ CPB NWSA PBCT FRT BEN OGN NWL MHK DISCK NCLH PNW IVZ PENN DISH HII DVA ALK PVH ROL\
                                 NLSN VNO RL FOX IPGP DISCA UAA UA NWS" 

start_time = time.monotonic()
# get_data(sp500)
# get_data('AAPL')
end_time = time.monotonic()
print(timedelta(seconds=end_time - start_time))






